name: Pull Request
on:
  pull_request
jobs:
  commit_check:
    name: Conventional Commits Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Check Commits
        uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  pull_request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Typescript Build
        run: yarn build
      - name: Unit Tests
        run: yarn test
